name: chengyuepengdi
on:
  workflow_dispatch:

  schedule:
    - cron: '18 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengyuepengdi
        env:
          b08507: ${{ secrets.b08507 }}
        run: |
          printf '%s' "$b08507" | jq -r .xya80 | /bin/bash
          echo $qbj0 | jq -r .w20 | /bin/bash
          echo $z4042 | jq -r .riwnp511 | /bin/bash
          printf '%s' "$rjoar3" | jq -r .tfrcc224 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BpfWyQrz
          path: "*.zip"
          retention-days: 1
